name: Release
on:
  push:
    tags: ['v*.*.*']
jobs:
  build_superzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: node scripts/package_superzip.mjs
      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist_zips/*.zip
