name: Security & Secrets
on:
  pull_request:
    branches: [ main ]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Secret scan (gitleaks)
        uses: zricethezav/gitleaks-action@v2
        with:
          args: '--verbose'
      - name: Audit
        run: npm audit --omit=dev || true