name: Security & Secrets / scan

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout (full history for PR range)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        id: gitleaks
        uses: gitleaks/gitleaks-action@v2
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >-
            detect
            --redact
            --report-format sarif
            --report-path results.sarif
            --exit-code 1
            --source .
            --no-git

      - name: Upload SARIF to GitHub Security tab
        if: always() && steps.gitleaks.outcome != 'cancelled' && hashFiles('results.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

      - name: Fail if Gitleaks detected issues
        if: steps.gitleaks.outcome == 'failure'
        run: exit 1
